[package]
name = "pmcli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
magic-crypt = "3.1.12"
rpassword = "7.2.0"
sha3 = "0.10.8"
